name: chi
version: 0.0.1
description: virtual pet in dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  color: any
  dartson: any
  paper_elements: any
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer
- dartson

